__title__ = 'frashfeed-python'
__description__ = 'News feed for Alexa.'
__url__ = 'https://github.com/alexiob/flashfeed-python'
__version__ = '1.0.1'
__author__ = 'Alessandro Iob'
__author_email__ = 'alessandro.iob@gmail.com'
__license__ = 'MIT'
__copyright__ = 'Copyright 2019 Alessandro Iob'
